In [1]:
print("kanmani")

kanmani


In [3]:
"kanmani"

'kanmani'

In [5]:
import numpy as np
arr1 = np.array([1,2,3])
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
arr2 = [1,2,3]
print(arr2)
print(type(arr2))

[1, 2, 3]
<class 'list'>


In [9]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
print(type(arr3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
