In [13]:
print("preetha")

preetha


In [14]:
"preetha"

'preetha'

In [15]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print (type(arr))


[1 2 3 4]
<class 'numpy.ndarray'>


In [16]:
arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2)


[[1 2 3]
 [4 5 6]]


In [17]:
arr_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1]:
#pip install numpy


In [15]:
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("Element at 0th row and 0th column of arr1 is:",arr1[0,0])
print("Element at 1st row and 2nd column  of arr1 is:",arr1[2,0])


Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at 0th row and 0th column of arr1 is: 0
Element at 1st row and 2nd column  of arr1 is: 8


In [9]:
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("\n")
print("1st row :\n",arr1[1])
print("2nd row:\n",arr1[2])


Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


1st row :
 [4 5 6 7]
2nd row:
 [ 8  9 10 11]


In [17]:
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(2,2,3)
print("Array arr1:\n",arr1)
print("Element:",arr1[1,0,2])


Array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element: 8


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
x_v = arr.view()

print(x)
print(x_v)


[1 2 3 4 5]
[42  2  3  4  5]


In [61]:
import numpy as np 
arr = np.arange(15)
arr1 = arr.reshape(3,5)
print(arr1)
print(arr1[2])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[10 11 12 13 14]


In [91]:
from numpy import random
x = random.randint(100)
print(x)

35


In [168]:
from numpy import random
symbol = ["stone","paper","scissors"]
player_1 = random.choice(symbol)
self = input("Enter your symbol:")
def hand(symbols):
    if(symbols  == "stone"):
            return("""
            _______
        ---'   ____)
              (_____)
              (_____)
              (____)
        ---.__(___)
        """)
    elif(symbols  == "paper"):
            return("""
             _______
        ---'    ____)____
                   ______)
                  _______)
                 _______)
        ---.__________)
        """)
    elif(symbols  == "scissors"):
            return("""
            _______
        ---'   ____)____
                  ______)
               __________)
              (____)
        ---.__(___)
        """)
print(f"The system chose:{hand(player_1)}")
print(f"You chose:{hand(self)}")



Enter your symbol: paper


The system chose:
            _______
        ---'   ____)
              (_____)
              (_____)
              (____)
        ---.__(___)
        
You chose:
             _______
        ---'    ____)____
                   ______)
                  _______)
                 _______)
        ---.__________)
        
